### ISSUE TITLE
my suggestion

### ISSUE THREAD

**Issue by mithuncoder** [poggersbutnot/python-javascript-obfuscator#2]
please add a input function to encrypt code.There is no input optoin like your python code obfuscator, so this code is hard to use.i tried many ways to deobfuscate your python code obfuscate script..unbreakable loop.

**Comment by poggersbutnot** [comment]
That's already in my unreleased version. Please give any other suggestions.

**Comment by mithuncoder** [comment]
> That's already in my unreleased version. Please give any other suggestions.

Waiting for the next level advanced python obfuscator🔥🔥🔥🔥

**Comment by poggersbutnot** [comment]
Thank you so much! It is completed (better not find any bugs...) and should be released today.

**Comment by poggersbutnot** [comment]
Thank you so much! It is completed (I better not find any more bugs...) and should be released today.

**Comment by poggersbutnot** [comment]
Thank you so much! It is completed and should be released today unless I find any more retched bugs.

**Comment by poggersbutnot** [comment]
Thank you so much! It is completed (I better not find any more bugs...) and should be released today. Unless I find any more bugs of-course but as of now it's done.

**Comment by poggersbutnot** [comment]
Thank you so much! It is completed and should be released today. Of-course that is unless I find any more bugs.

**Comment by poggersbutnot** [comment]
Done. https://github.com/poggersbutnot/pbn_obfuscator
